app:
  port: # 3000 by default
  env: # anything other than 'production' will be treated as 'development'

database:
  mongo_url:
  logging: # the value you provide will be typecasted to boolean (0, '', false will be treated as false)

jwt:
  secret:
  expiresIn: # should be a number (in seconds)
  refreshTokenSecret:
  refreshTokenExpiresIn: # should be a number (in seconds)

swagger:
  # basic swagger auth guard will be enabled if 'both' user and password are providedØ
  user:
  password:
